### ISSUE TITLE
_Namespace exceptions 

### ISSUE THREAD

**Issue by jeepshop** [sass/migrator#184]
I've installed the latest 1.3.8 migration tool into visual studio (Win 10 64 bit) using "npm install -g sass-migrator" without issue. And I can run the script without parameters just fine and it returns the help instructions.

However if I execute either of the following commands, on any sass file, all I get is a dart Exception.

sass-migrator module sample.scss
sass-migrator namespace sample.scss

It would appear the problem is with the followLinks() call in Dart, maybe a permissions issue? But for the life of my can't get past this issue.

`
Unsupported operation: _Namespace
    at Object.wrapException (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:1208:17)
    at Object._Namespace__namespace (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:6606:15)
    at _Directory.listSync$2$followLinks$recursive (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:17754:14)
    at LocalDirectory.listSync$2$followLinks$recursive (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19061:30)
    at LocalDirectory.listSync$1$followLinks (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19066:19)
    at _ListTreeNode.listSync$3$followLinks (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19548:101)
    at ListTree_listSync_closure.call$1 (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19483:43)
    at ExpandIterator.moveNext$0 (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:13348:37)
    at Object.List_List$_of (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:5157:49)
    at Object.List_List$of (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:5148:18) {
  dartException: <ref *1> UnsupportedError {
    message: '_Namespace',
    '$thrownJsError': <ref *2> Unsupported operation: _Namespace
        at Object.wrapException (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:1208:17)
        at Object._Namespace__namespace (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:6606:15)
        at _Directory.listSync$2$followLinks$recursive (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:17754:14)
        at LocalDirectory.listSync$2$followLinks$recursive (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19061:30)
        at LocalDirectory.listSync$1$followLinks (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19066:19)
        at _ListTreeNode.listSync$3$followLinks (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19548:101)
        at ListTree_listSync_closure.call$1 (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:19483:43)
        at ExpandIterator.moveNext$0 (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:13348:37)
        at Object.List_List$_of (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:5157:49)
        at Object.List_List$of (C:\Users\someuser\AppData\Roaming\npm\node_modules\sass-migrator\sass-migrator.dart.js:5148:18) {
      dartException: [Circular *1],
      '$cachedTrace': _StackTrace {
        _exception: [Circular *2],
        _trace: 'Unsupported operation: _Namespace\n' +
          '    at Object.wrapException (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:1208:17)\n' +
          '    at Object._Namespace__namespace (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:6606:15)\n' +
          '    at _Directory.listSync$2$followLinks$recursive (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:17754:14)\n' +
          '    at LocalDirectory.listSync$2$followLinks$recursive (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:19061:30)\n' +
          '    at LocalDirectory.listSync$1$followLinks (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:19066:19)\n' +
          '    at _ListTreeNode.listSync$3$followLinks (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:19548:101)\n' +
          '    at ListTree_listSync_closure.call$1 (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:19483:43)\n' +
          '    at ExpandIterator.moveNext$0 (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:13348:37)\n' +
          '    at Object.List_List$_of (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:5157:49)\n' +
          '    at Object.List_List$of (C:\\Users\\someuser\\AppData\\Roaming\\npm\\node_modules\\sass-migrator\\sass-migrator.dart.js:5148:18)'
      }
    }
  }
}`

**Comment by jathak** [comment]
Hmm. It looks like there was some issue with the null-safety migration that only manifests on Node, and our CI was misconfigured so those tests got skipped. I'll look into this.

For now, you can install 1.3.7 with `npm install -g sass-migrator@1.3.7`.

**Comment by jathak** [comment]
The fix should now be released in 1.3.9. Sorry for the trouble!

**Comment by jeepshop** [comment]
I can confirm this was fixed in 1.3.9. Thanks for all your help @jathak.
