### ISSUE TITLE
Unhandled null pointer exception on Dart Sass-Migrator and Sass-Migrator.js

### ISSUE THREAD

**Issue by juliankrieger** [sass/migrator#199]
1. Install Sass-Migrator: `brew install sass/sass/migrator`
2. Run `sass-migrator module --verbose index.scss`
3. Experience crash. 

Stack Trace:
```
Unhandled exception:
Null check operator used on a null value
#0      _ReferenceVisitor.visitVariableExpression (package:sass_migrator/src/migrators/module/references.dart:666)
#1      VariableExpression.accept (package:sass/src/ast/sass/expression/variable.dart:24)
#2      RecursiveAstVisitor.visitExpression (package:sass/src/visitor/recursive_ast.dart:17)
#3      NullableExtension.andThen (package:sass/src/util/nullable.dart:12)
#4      RecursiveStatementVisitor.visitDeclaration (package:sass/src/visitor/recursive_statement.dart:47)
#5      Declaration.accept (package:sass/src/ast/sass/statement/declaration.dart:58)
#6      RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:202)
#7      _ReferenceVisitor.visitChildren (package:sass_migrator/src/migrators/module/references.dart:560)
#8      RecursiveStatementVisitor.visitStyleRule (package:sass/src/visitor/recursive_statement.dart:123)
#9      StyleRule.accept (package:sass/src/ast/sass/statement/style_rule.dart:26)
#10     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:202)
#11     _ReferenceVisitor.visitChildren (package:sass_migrator/src/migrators/module/references.dart:560)
#12     RecursiveStatementVisitor.visitStyleRule (package:sass/src/visitor/recursive_statement.dart:123)
#13     StyleRule.accept (package:sass/src/ast/sass/statement/style_rule.dart:26)
#14     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:202)
#15     _ReferenceVisitor.visitStylesheet (package:sass_migrator/src/migrators/module/references.dart:350)
#16     _ReferenceVisitor._loadUseOrForward (package:sass_migrator/src/migrators/module/references.dart:457)
#17     _ReferenceVisitor.visitUseRule (package:sass_migrator/src/migrators/module/references.dart:416)
#18     UseRule.accept (package:sass/src/ast/sass/statement/use_rule.dart:51)
#19     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:202)
#20     _ReferenceVisitor.visitStylesheet (package:sass_migrator/src/migrators/module/references.dart:350)
#21     _ReferenceVisitor.visitImportRule (package:sass_migrator/src/migrators/module/references.dart:385)
#22     ImportRule.accept (package:sass/src/ast/sass/statement/import_rule.dart:21)
#23     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:202)
#24     _ReferenceVisitor.visitStylesheet (package:sass_migrator/src/migrators/module/references.dart:350)
#25     _ReferenceVisitor.visitImportRule (package:sass_migrator/src/migrators/module/references.dart:385)
#26     ImportRule.accept (package:sass/src/ast/sass/statement/import_rule.dart:21)
#27     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:202)
#28     _ReferenceVisitor.visitStylesheet (package:sass_migrator/src/migrators/module/references.dart:350)
#29     _ReferenceVisitor.build (package:sass_migrator/src/migrators/module/references.dart:280)
#30     new References (package:sass_migrator/src/migrators/module/references.dart:180)
#31     ModuleMigrator.migrateFile (package:sass_migrator/src/migrators/module.dart:95)
#32     Migrator.run (package:sass_migrator/src/migrator.dart:97)
#33     ModuleMigrator.run (package:sass_migrator/src/migrators/module.dart:70)
#34     CommandRunner.runCommand (package:args/command_runner.dart:196)
#35     MigratorRunner.execute (package:sass_migrator/src/runner.dart:83)
#36     main (file:///private/tmp/migrator-20210622-85768-1w1n7x7/migrator-1.5.0/bin/sass_migrator.dart:17)
#37     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

For the JS Version:

1. Install Sass-Migrator: `npm i -g sass-migrator`
2. Run Sass-Migrator: `sass-migrator --dry-run module index.scss`
3. Experience Crash

Stack Trace:

```
/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:15841
      throw error;
      ^

TypeError: Cannot read property 'toString' of null
    at _ReferenceVisitor.visitVariableExpression$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:35447:14)
    at VariableExpression.accept$1$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22229:22)
    at VariableExpression.accept$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22232:19)
    at _ReferenceVisitor.visitExpression$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:32148:18)
    at Object.eval (eval at Closure_forwardCallTo (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:1577:14), <anonymous>:3:39)
    at Object.NullableExtension_andThen (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:11274:40)
    at Declaration.accept$1$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22419:9)
    at Declaration.accept$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22424:19)
    at _ReferenceVisitor.visitChildren$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:32316:26)
    at _ReferenceVisitor.visitChildren$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:35336:13) {
  dartException: NullError {
    '__js_helper$_message': "Cannot read property 'toString' of null",
    _method: 'toString',
    '$thrownJsError': <ref *1> TypeError: Cannot read property 'toString' of null
        at _ReferenceVisitor.visitVariableExpression$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:35447:14)
        at VariableExpression.accept$1$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22229:22)
        at VariableExpression.accept$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22232:19)
        at _ReferenceVisitor.visitExpression$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:32148:18)
        at Object.eval (eval at Closure_forwardCallTo (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:1577:14), <anonymous>:3:39)
        at Object.NullableExtension_andThen (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:11274:40)
        at Declaration.accept$1$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22419:9)
        at Declaration.accept$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22424:19)
        at _ReferenceVisitor.visitChildren$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:32316:26)
        at _ReferenceVisitor.visitChildren$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:35336:13) {
      '$cachedTrace': _StackTrace {
        _exception: [Circular *1],
        _trace: "TypeError: Cannot read property 'toString' of null\n" +
          '    at _ReferenceVisitor.visitVariableExpression$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:35447:14)\n' +
          '    at VariableExpression.accept$1$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22229:22)\n' +
          '    at VariableExpression.accept$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22232:19)\n' +
          '    at _ReferenceVisitor.visitExpression$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:32148:18)\n' +
          '    at Object.eval (eval at Closure_forwardCallTo (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:1577:14), <anonymous>:3:39)\n' +
          '    at Object.NullableExtension_andThen (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:11274:40)\n' +
          '    at Declaration.accept$1$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22419:9)\n' +
          '    at Declaration.accept$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:22424:19)\n' +
          '    at _ReferenceVisitor.visitChildren$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:32316:26)\n' +
          '    at _ReferenceVisitor.visitChildren$1 (/usr/local/lib/node_modules/sass-migrator/sass-migrator.dart.js:35336:13)'
      }
    }
  }
}

```

**Comment by jathak** [comment]
It looks like there's some case where the a `VariableDeclaration` is in scope, but its source isn't being set in `_declarationSources`. I'm not sure where this could be.

Could you provide a reproduction?

**Comment by Omcsesz** [comment]
I tried to reproduce the issue, but it works for me with the latest version. It outputs:
`Nothing to migrate!` now.
@juliankrieger is it the same on your side?
