### ISSUE TITLE
Unhandled exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by stof** [sass/migrator#244]
when running the module migrator on my entrypoint using a bunch of imports (for files that have already been migrated with the migrator before), I'm getting this error with the following stack trace:

```
#0      _ReferenceVisitor.visitIncludeRule (package:sass_migrator/src/migrators/module/references.dart:671)
#1      IncludeRule.accept (package:sass/src/ast/sass/statement/include_rule.dart:62)
#2      RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:107)
#3      _ReferenceVisitor.visitChildren (package:sass_migrator/src/migrators/module/references.dart:538)
#4      RecursiveStatementVisitor.visitStylesheet (package:sass/src/visitor/recursive_statement.dart:80)
#5      RecursiveAstVisitor.visitStyleRule (package:sass/src/visitor/recursive_ast.dart:121)
#6      StyleRule.accept (package:sass/src/ast/sass/statement/style_rule.dart:30)
#7      RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:107)
#8      _ReferenceVisitor.visitChildren (package:sass_migrator/src/migrators/module/references.dart:538)
#9      RecursiveStatementVisitor.visitStylesheet (package:sass/src/visitor/recursive_statement.dart:80)
#10     RecursiveAstVisitor.visitStyleRule (package:sass/src/visitor/recursive_ast.dart:121)
#11     StyleRule.accept (package:sass/src/ast/sass/statement/style_rule.dart:30)
#12     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:107)
#13     _ReferenceVisitor.visitStylesheet (package:sass_migrator/src/migrators/module/references.dart:328)
#14     _ReferenceVisitor.visitImportRule (package:sass_migrator/src/migrators/module/references.dart:363)
#15     ImportRule.accept (package:sass/src/ast/sass/statement/import_rule.dart:25)
#16     RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:107)
#17     _ReferenceVisitor.visitStylesheet (package:sass_migrator/src/migrators/module/references.dart:328)
#18     _ReferenceVisitor.build (package:sass_migrator/src/migrators/module/references.dart:260)
#19     new References (package:sass_migrator/src/migrators/module/references.dart:166)
#20     ModuleMigrator.migrateFile (package:sass_migrator/src/migrators/module.dart:88)
#21     Migrator.run (package:sass_migrator/src/migrator.dart:96)
#22     ModuleMigrator.run (package:sass_migrator/src/migrators/module.dart:63)
#23     CommandRunner.runCommand (package:args/command_runner.dart:212)
#24     MigratorRunner.execute (package:sass_migrator/src/runner.dart:87)
#25     main (file:///home/runner/work/migrator/migrator/bin/sass_migrator.dart:17)
#26     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

I'm using version 1.7.3 of the migrator.

**Comment by jathak** [comment]
Sorry for the late response here. Were you able to find a minimal reproduction for this?
