### ISSUE TITLE
Crashes when a non-existent path is passed

### ISSUE THREAD

**Issue by nex3** [sass/migrator#55]
When a path to a file that doesn't exist is passed to the migrator, it crashes:

```shellsession
$ dart bin/sass_migrator.dart division asdf
Unhandled exception:
NoSuchMethodError: The getter 'scheme' was called on null.
Receiver: null
Tried calling: scheme
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      FilesystemImporter.canonicalize (package:sass/src/importer/filesystem.dart:24:13)
#2      parseStylesheet (package:sass_migrator/src/utils.dart:29:42)
#3      MigrationVisitor.run (package:sass_migrator/src/migration_visitor.dart:46:21)
#4      DivisionMigrator.migrateFile (package:sass_migrator/src/migrators/division.dart:38:12)
#5      Migrator.run (package:sass_migrator/src/migrator.dart:48:22)
#6      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#7      MigratorRunner.execute (package:sass_migrator/runner.dart:45:26)
<asynchronous suspension>
#8      main (file:///home/nweiz/sass/migrator/bin/sass_migrator.dart:16:20)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by nex3** [comment]
Looks like this has already been fixed.
