### ISSUE TITLE
Crashes on a URL that can't be loaded

### ISSUE THREAD

**Issue by nex3** [sass/migrator#57]
When the migrator encounters a URL that can't be loaded in `--migrate-deps` mode, it crashes:

```shellsession
$ echo "@import 'asdf';" > test.scss
$ dart bin/sass_migrator.dart division -d test.scss
Unhandled exception:
Invalid argument (uri): Value must be a String or a Uri: null
#0      _parseUri (package:path/src/context.dart:1065:3)
#1      Context.fromUri (package:path/src/context.dart:986:44)
#2      fromUri (package:path/path.dart:410:32)
#3      FilesystemImporter.load (package:sass/src/importer/filesystem.dart:30:16)
#4      parseStylesheet (package:sass_migrator/src/utils.dart:30:36)
#5      MigrationVisitor.visitDependency (package:sass_migrator/src/migration_visitor.dart:71:22)
#6      MigrationVisitor.visitImportRule (package:sass_migrator/src/migration_visitor.dart:99:11)
#7      ImportRule.accept (package:sass/src/ast/sass/statement/import_rule.dart:21:55)
#8      RecursiveStatementVisitor.visitChildren (package:sass/src/visitor/recursive_statement.dart:215:13)
#9      RecursiveStatementVisitor.visitStylesheet (package:sass/src/visitor/recursive_statement.dart:133:41)
#10     MigrationVisitor.visitStylesheet (package:sass_migrator/src/migration_visitor.dart:60:11)
#11     MigrationVisitor.run (package:sass_migrator/src/migration_visitor.dart:46:5)
#12     DivisionMigrator.migrateFile (package:sass_migrator/src/migrators/division.dart:38:12)
#13     Migrator.run (package:sass_migrator/src/migrator.dart:48:22)
#14     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#15     MigratorRunner.execute (package:sass_migrator/runner.dart:45:26)
<asynchronous suspension>
#16     main (file:///home/nweiz/sass/migrator/bin/sass_migrator.dart:16:20)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by nex3** [comment]
This also happens with the module migrator without `--migrate-deps`.
